#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestApp.Crosscutting.Email.Templates.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class RecoveryClueTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"

    public LoginTestApp.Crosscutting.Email.Templates.Models.RecoveryClueModel Model { get; set; }

    public string Subject
    {
        get { return "Password Recovery - Recovery Clue Requested"; }
    }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n    ");



WriteLiteral("\r\n");


            
            #line 16 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.CustomerName))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Dear <b>");


            
            #line 18 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"
              Write(Model.CustomerName);

            
            #line default
            #line hidden
WriteLiteral("</b></p>\r\n");


            
            #line 19 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <p></p>\r\n    <p>You have requested your recovery clue for your account at <b>" +
"");


            
            #line 21 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"
                                                               Write(Model.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</b>.</p>\r\n    <p></p>\r\n    <p>Please find it below. </p>\r\n    <p></p>\r\n    <p>Re" +
"covery Clue: ");


            
            #line 25 "..\..\Email\Templates\Views\RecoveryClueTemplate.cshtml"
                 Write(Model.RecoveryClue);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    <p></p>\r\n    <p>If you received this email due to an error, you can saf" +
"ely ignore it.</p>\r\n\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
