#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestApp.Crosscutting.Email.Templates.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ResetLinkTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"

    public LoginTestApp.Crosscutting.Email.Templates.Models.ResetLinkModel Model { get; set; }

    public string Subject
    {
        get { return "Password Recovery - Reset Link Requested"; }
    }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n    ");



WriteLiteral("\r\n");


            
            #line 16 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.CustomerName))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Dear <b>");


            
            #line 18 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"
              Write(Model.CustomerName);

            
            #line default
            #line hidden
WriteLiteral("</b></p>\r\n");


            
            #line 19 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <p></p>\r\n    <p>You have requested to have your password reset for your accou" +
"nt at <b>");


            
            #line 21 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"
                                                                        Write(Model.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</b>.</p>\r\n    <p></p>\r\n    <p>Please visit below link to reset your password. </" +
"p>\r\n    <p></p>\r\n    <p><a href=\"");


            
            #line 25 "..\..\Email\Templates\Views\ResetLinkTemplate.cshtml"
           Write(Model.Url);

            
            #line default
            #line hidden
WriteLiteral("\">Reset Password Link</a></p>\r\n    <p></p>\r\n    <p>If you received this email due" +
" to an error, you can safely ignore it.</p>\r\n\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
