//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestApp.DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginTestApp.DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--This script is inteded to setup everything in regards of the Core functionality for the application
        ///
        ///-- Roles Setup
        ///INSERT INTO Roles (Name, [Description], IsActive)
        ///VALUES(&apos;Administrator&apos;, &apos;System administrator full granted access to the system features&apos;, 1)
        ///
        ///--INSERT INTO Roles (Name, [Description], IsActive)
        ///--VALUES(&apos;Anonymous&apos;, &apos;System administrator limited access to the system features&apos;, 1)
        ///
        ///-- Users Setup
        ///INSERT INTO Users (Alias, FullName, [Password], Email, PhoneNumber, PasswordRecove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreSetup_Sql {
            get {
                return ResourceManager.GetString("CoreSetup_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.[ModelBaseTableName]
        ///  ADD DEFAULT (USER_NAME()) FOR [CreatedBy] 
        ///
        ///ALTER TABLE dbo.[ModelBaseTableName]
        ///  ADD DEFAULT (GETUTCDATE()) FOR [CreatedDate] 
        ///.
        /// </summary>
        internal static string ModelBase_Sql {
            get {
                return ResourceManager.GetString("ModelBase_Sql", resourceCulture);
            }
        }
    }
}
